model:
  name: "facebook/opt-125m"
  maxModelLen: 2048
  trustRemoteCode: false

replicaCount: 1

resources:
  requests:
    memory: "4Gi"
    nvidia.com/gpu: "1"
  limits:
    memory: "8Gi"
    nvidia.com/gpu: "1"
