{{- if not .Values.litellm.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm-registry.masterSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "litellm-registry.name" . }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.litellm.existingSecretKey }}: {{ .Values.litellm.masterKey | quote }}
{{- end }}
